require "ifj21"

function main()

    local n:nil = a

    if x == nil + a then
        write("yes\n")
    else
        write("no\n")
    end

    if y == nil then
        write("yes\n")
    else
        write("no\n")
    end

    if z == nil then
        write("yes\n")
    else
        write("no\n")
    end

    if n == nil then
        write("yes\n")
    else
        write("no\n")
    end
end

main()